package com.xxx.ency.model.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xxx.ency.model.bean.CheckWarehouse;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHECK_WAREHOUSE".
*/
public class CheckWarehouseDao extends AbstractDao<CheckWarehouse, Long> {

    public static final String TABLENAME = "CHECK_WAREHOUSE";

    /**
     * Properties of entity CheckWarehouse.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Userid = new Property(1, String.class, "userid", false, "USERID");
        public final static Property WarehouseNo = new Property(2, String.class, "WarehouseNo", false, "WAREHOUSE_NO");
        public final static Property ResultJson = new Property(3, String.class, "resultJson", false, "RESULT_JSON");
        public final static Property Date = new Property(4, String.class, "date", false, "DATE");
        public final static Property Type = new Property(5, String.class, "type", false, "TYPE");
    }


    public CheckWarehouseDao(DaoConfig config) {
        super(config);
    }
    
    public CheckWarehouseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHECK_WAREHOUSE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USERID\" TEXT," + // 1: userid
                "\"WAREHOUSE_NO\" TEXT," + // 2: WarehouseNo
                "\"RESULT_JSON\" TEXT," + // 3: resultJson
                "\"DATE\" TEXT," + // 4: date
                "\"TYPE\" TEXT);"); // 5: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHECK_WAREHOUSE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CheckWarehouse entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userid = entity.getUserid();
        if (userid != null) {
            stmt.bindString(2, userid);
        }
 
        String WarehouseNo = entity.getWarehouseNo();
        if (WarehouseNo != null) {
            stmt.bindString(3, WarehouseNo);
        }
 
        String resultJson = entity.getResultJson();
        if (resultJson != null) {
            stmt.bindString(4, resultJson);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(5, date);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CheckWarehouse entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userid = entity.getUserid();
        if (userid != null) {
            stmt.bindString(2, userid);
        }
 
        String WarehouseNo = entity.getWarehouseNo();
        if (WarehouseNo != null) {
            stmt.bindString(3, WarehouseNo);
        }
 
        String resultJson = entity.getResultJson();
        if (resultJson != null) {
            stmt.bindString(4, resultJson);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(5, date);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CheckWarehouse readEntity(Cursor cursor, int offset) {
        CheckWarehouse entity = new CheckWarehouse( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // WarehouseNo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // resultJson
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // date
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CheckWarehouse entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWarehouseNo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setResultJson(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDate(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CheckWarehouse entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CheckWarehouse entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CheckWarehouse entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
