package com.xxx.ency.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xxx.ency.model.bean.CheckWarehouse;
import com.xxx.ency.model.bean.CheckWork;
import com.xxx.ency.model.bean.FixedCheckBean;
import com.xxx.ency.model.bean.LikeBean;

import com.xxx.ency.model.db.CheckWarehouseDao;
import com.xxx.ency.model.db.CheckWorkDao;
import com.xxx.ency.model.db.FixedCheckBeanDao;
import com.xxx.ency.model.db.LikeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig checkWarehouseDaoConfig;
    private final DaoConfig checkWorkDaoConfig;
    private final DaoConfig fixedCheckBeanDaoConfig;
    private final DaoConfig likeBeanDaoConfig;

    private final CheckWarehouseDao checkWarehouseDao;
    private final CheckWorkDao checkWorkDao;
    private final FixedCheckBeanDao fixedCheckBeanDao;
    private final LikeBeanDao likeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        checkWarehouseDaoConfig = daoConfigMap.get(CheckWarehouseDao.class).clone();
        checkWarehouseDaoConfig.initIdentityScope(type);

        checkWorkDaoConfig = daoConfigMap.get(CheckWorkDao.class).clone();
        checkWorkDaoConfig.initIdentityScope(type);

        fixedCheckBeanDaoConfig = daoConfigMap.get(FixedCheckBeanDao.class).clone();
        fixedCheckBeanDaoConfig.initIdentityScope(type);

        likeBeanDaoConfig = daoConfigMap.get(LikeBeanDao.class).clone();
        likeBeanDaoConfig.initIdentityScope(type);

        checkWarehouseDao = new CheckWarehouseDao(checkWarehouseDaoConfig, this);
        checkWorkDao = new CheckWorkDao(checkWorkDaoConfig, this);
        fixedCheckBeanDao = new FixedCheckBeanDao(fixedCheckBeanDaoConfig, this);
        likeBeanDao = new LikeBeanDao(likeBeanDaoConfig, this);

        registerDao(CheckWarehouse.class, checkWarehouseDao);
        registerDao(CheckWork.class, checkWorkDao);
        registerDao(FixedCheckBean.class, fixedCheckBeanDao);
        registerDao(LikeBean.class, likeBeanDao);
    }
    
    public void clear() {
        checkWarehouseDaoConfig.clearIdentityScope();
        checkWorkDaoConfig.clearIdentityScope();
        fixedCheckBeanDaoConfig.clearIdentityScope();
        likeBeanDaoConfig.clearIdentityScope();
    }

    public CheckWarehouseDao getCheckWarehouseDao() {
        return checkWarehouseDao;
    }

    public CheckWorkDao getCheckWorkDao() {
        return checkWorkDao;
    }

    public FixedCheckBeanDao getFixedCheckBeanDao() {
        return fixedCheckBeanDao;
    }

    public LikeBeanDao getLikeBeanDao() {
        return likeBeanDao;
    }

}
